project/src/java/display/DisplayProductMB.java
package display;

import dao.ListDao;
import entity.Product;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "obj4")
@SessionScoped
public class DisplayProductMB 
{ 
    Product product = new Product(); 
    private Product selectedProduct;
    
    
    
    public Product getSelectedProduct() {
        return selectedProduct;
    }

    public void setSelectedProduct(Product selectedProduct) {
        this.selectedProduct = selectedProduct;
    }
    
    public Product getProduct() { 
        return product;
    } 

    public void setProduct(Product product) { 
        this.product = product;
    } 
    
    public List<Product> getAllProduct() 
    { 
        List<Product> plist = new ListDao().allProductList();
        return plist;
    } 
} 

project/web/display.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 
    
    
    <h:head> 
        <title>ProgGyan ONLINE</title> 
    </h:head> 
    
    
    
    
    <h:body> 
        <f:view> 
            <h:form id="form"> 
                <p:dataGrid var="product" value="#{obj4.allProduct}" columns="5" rows="5" paginator="true" id="p" 
                            paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}" rowsPerPageTemplate="6,12,16">
                    
                    <f:facet name="header"> 
                        <h:outputLabel value="All Products"/> 
                    </f:facet> 
                    
                    
                    <p:panel header="#{product.proName}">
                        <h:panelGrid columns="1">
                            <h:graphicImage name="#{product.proImgUrl}" library="images" width="180" height="200"/>
                            <h:outputText  value="#{product.proPrice} TK/-"/>
                        </h:panelGrid> 
                        
                        <p:commandLink update=":form:pro" oncomplete="PF('proDetails').show()" title="View Details">
                            <!-- <h:outputText styleClass="ui-icon ui-icon-search"/> --> 
                            <h:outputText value="Details"/> 
                            <f:setPropertyActionListener value="#{product}" target="#{obj4.selectedProduct}"/>
                        </p:commandLink> 
                    </p:panel> 
                </p:dataGrid> 
                
                
                
                
                
                
                <p:dialog header="Product Info" widgetVar="proDetails" modal="true" 
                          showEffect="fade" hideEffect="fade" rendererType="false"> 
                        
                    <p:outputPanel id="pro"> 
                        <p:panelGrid columns="2" styleClass="ui-responsive"> 
                            <f:facet name="header"> 
                                <h:graphicImage name="#{obj4.selectedProduct.proImgUrl}" library="images" width="180" height="215"/> 
                            </f:facet> 
                            
                            <h:outputText value="Product Name"/> 
                            <h:outputText value="#{obj4.selectedProduct.proName}"/> 

                            <h:outputText value="Product Price"/> 
                            <h:outputText value="#{obj4.selectedProduct.proPrice} BDT"/> 

                            <h:outputText value="Description"/> 
                            <h:outputText value="#{obj4.selectedProduct.proDesc}"/> 
                        </p:panelGrid> 
                    </p:outputPanel> 
                </p:dialog> 
            </h:form> 
        </f:view> 
    </h:body> 
</html> 

project/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"> 
    <h:head> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
        
        <title>ProgGyan ONLINE</title>
    </h:head>
    <h:body> 
        Hello from Facelets 
    </h:body>
</html>

project/web/newTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Facelets Template</title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="top">Top</ui:insert>
        </div>
        <div>
            <div id="left">
                <ui:insert name="left">Left</ui:insert>
            </div>
            <div>
                <div id="right">
                    <ui:insert name="right">Right</ui:insert>
                </div>
                <div id="content" class="right_content">
                    <ui:insert name="content">Content</ui:insert>
                </div>
            </div>
        </div>
        <div id="bottom">
            <ui:insert name="bottom">Bottom</ui:insert>
        </div>

    </h:body>

</html>